### ISSUE TITLE
Mistake in regex in the Prometheus scrape config for the node exporter endpoints

### ISSUE THREAD

**Issue by StefaanSeys** [ehlesp/smallab-k8s-pve-guide#14]
## Where's the issue located

- G035 - Deploying services 04 ~ Monitoring stack - Part 4 - Prometheus server
- https://github.com/ehlesp/smallab-k8s-pve-guide/blob/main/G035%20-%20Deploying%20services%2004%20~%20Monitoring%20stack%20-%20Part%204%20-%20Prometheus%20server.md#configuration-file-prometheusyaml

## What's the problem

The regex 'node-exporter' is not matching the endpoint name, which is "mntr-agent-prometheus-node-exporter".
The easy fix is to replace the regex with '.*node-exporter'.

```
- job_name: 'node-exporter'
    scrape_interval: 55s
    kubernetes_sd_configs:
      - role: endpoints
    relabel_configs:
    - source_labels: [__meta_kubernetes_endpoints_name]
      regex: 'node-exporter'
      action: keep
```
should be
```
- job_name: 'node-exporter'
    scrape_interval: 55s
    kubernetes_sd_configs:
      - role: endpoints
    relabel_configs:
    - source_labels: [__meta_kubernetes_endpoints_name]
      regex: '.*node-exporter'
      action: keep
```

Great guide by the way!
